### ISSUE TITLE
Missing include

### ISSUE THREAD

**Issue by KingDuckZ** [rmind/ringbuf#10]
I'm compiling this with gcc 8.3.0 and I get a build error on `ssize_t`. I think ringbuf.h is missing an `#include <sys/types.h>` at the top.

*Edit* never mind, I think the code works without changes if I make sure all the macros are defined following the content of the makefile

**Comment by rmind** [comment]
Why not include types before including ringbuf.h? Developers have different preferences on whether to include the type headers in the library header or let the user of the library include all relevant headers.
