### ISSUE TITLE
Original message-sizes

### ISSUE THREAD

**Issue by ulatekh** [rmind/ringbuf#4]
After reviewing the code, I found something that wasn't mentioned in the README file -- the original message-sizes aren't preserved. If several contiguous messages are ready to be consumed, they're all returned together, as one buffer. That's not a big problem for my expected use-case, but it's something that must be realized. Perhaps a small addition to the documentation?

Also, I found an unlikely, but possible, fault case. If ringbuf_acquire() is called, but ringbuf_unregister() is called before calling ringbuf_produce() (or the app somehow crashes after ringbuf_acquire() but before ringbuf_produce()), that part of the ring-buffer will contain stale/gibberish data, probably confusing the client to no end. Given that multiple produced-messages can be returned in a single call to ringbuf_consume(), valid messages could be lost too. I don't have an obvious solution for this yet. Client responsibility to check message-body CRCs?

**Comment by rmind** [comment]
- Correct. It is a **buffer**, so you operate on a **stream**. It does not really make sense to preserve the message sizes. As noted in the PR, it is useful to consume as much as possible (think of the read()/fread() semantics) to maximise the throughput. If the ring buffer is used to pass the messages, then it is the caller's responsibility to implement its own message encoding (e.g. reserve the first integer for the message length). However, as noted in the README, this implementation does preserve the message **boundaries** (so, the consumer can get multiple messages, but not a partial message). Why is this useful? Typically, you would have to implement FSM to parse the stream on the fly. In this case, you can just rely on your data/message encoding.
- Crash-resistance is just best-effort in such algorithms. The idea is that if you process crashes somewhere else without calling `ringbuf_unregister()`, it doesn't immediately derail all other workers. If your process crashes in the middle of `ringbuf_acquire()` -- tough luck. :) Recovery and consistency mechanisms are beyond this library.

P.S. I have been contemplating crash-safe concurrent data structures recently, though. It seems there are not many papers on this subject. On the other hand, it's difficult.

**Comment by rmind** [comment]
From the "Notes" section in the README file:
> If you think of produced range as a message, then consumer will return a **block** of messages, always ending at the message boundary. 

Since this point is already mentioned in the document, I think this issue can be resolved.
