### ISSUE TITLE
multiple ringbuf_acquire() by one thread with one ringbuf_produce() call

### ISSUE THREAD

**Issue by usergoodvery** [rmind/ringbuf#7]
Hi
If we have a situation where a producer thread issues multiple ringbuf_acquire(ringbuf, w, len)) so each successive call returns a different slot offset. Now let's say I do save one value into one of those slots and not the others. I then issue a single ringbuf_produce(ringbuf, w). From reading the code that will trick the consumer into reading from a range that don't have values in them because ringbuf_produce() will do a atomic_store_explicit(&w->seen_off, RBUF_OFF_MAX, memory_order_relaxed) for the whole producer thread. 
Is the above correct ? It is probably a misuse of the ringbuffer I just wanted to confirm my understanding of your semantics.

**Comment by rmind** [comment]
- Nested `ringbuf_acquire()` calls are not allowed by the API.  I just updated the documention to clarify this aspect.
- Another `ringbuf_acquire()` call would behave **almost** like a `ringbuf_publish()` with the respect to previously acquired range. I say almost because it would not issue a relevant memory fence, so it would not guarantee that the previous range ("message") gets published correctly.

**Comment by usergoodvery** [comment]
just to clarify when you say 'nested' I took it that you meant consecutive without intervening ringbuf_produce() calls between each ringbuf_acquire() call?

**Comment by rmind** [comment]
That's right. Perhaps "consecutive" is a better word here.

**Comment by usergoodvery** [comment]
Thanks for confirming. I like the simplicity of your implementation, as you see what's going on underneath. And the test you provide is quite convincing. Is this work based on some known algorithm?

**Comment by rmind** [comment]
Not that I am aware of, but I was inspired by the quiescent state-based reclamation algorithms (like RCU or EBR). If you think about it, the consumer is just trying to reclaim the memory. Plus some usual lock-free programming tricks, e.g. sequence/generation number is a common way to solve an ABA problem.

**Comment by rmind** [comment]
Resolved.
